env: dev
hikari:
  connection-timeout: 30000
  maximum-pool-size: 10
  max-lifetime: 1800000
  idle-timeout: 600000
  leak-detection-threshold: 8000
  pool-name: subjectsDbPool
  register-mbeans: true
  matchsource-debug-enabled: true
